name: Scan periodic
on:
  schedule:
    - cron: '15 3 * * *'

permissions:
  contents: read

jobs:
  trivy:
    permissions:
      contents: read
      security-events: write
    uses: "./.github/workflows/common-trivy.yaml"
    with:
      upload-to-github-security-tab: true
